---
apiVersion: v1
kind: ServiceAccount
metadata:
  annotations:
    prometheus.io/port: "8080"
    prometheus.io/scheme: http
    app.quarkus.io/commit-id: b38f9a5fd09f6fe2c5c09bfcdee800d5908d41e8
    app.quarkus.io/vcs-url: https://github.com/independentid/i2scim.git
    app.quarkus.io/build-timestamp: 2021-06-29 - 17:36:09 +0000
    prometheus.io/scrape: "true"
    prometheus.io/path: /metrics
  labels:
    app.kubernetes.io/name: i2scim-mongo
    app.kubernetes.io/version: 0.7.0-Alpha
  name: i2scim-mongo
  namespace: scim-mongo
---
apiVersion: v1
kind: Service
metadata:
  annotations:
    prometheus.io/port: "8080"
    prometheus.io/scheme: http
    app.quarkus.io/commit-id: b38f9a5fd09f6fe2c5c09bfcdee800d5908d41e8
    app.quarkus.io/vcs-url: https://github.com/independentid/i2scim.git
    app.quarkus.io/build-timestamp: 2021-06-29 - 17:36:09 +0000
    prometheus.io/scrape: "true"
    prometheus.io/path: /metrics
  labels:
    app.kubernetes.io/name: i2scim-mongo
    app.kubernetes.io/version: 0.7.0-Alpha
  name: i2scim-mongo
  namespace: scim-mongo
spec:
  ports:
    - name: http
      port: 8080
      targetPort: 8080
  selector:
    app.kubernetes.io/name: i2scim-mongo
    app.kubernetes.io/version: 0.7.0-Alpha
  type: LoadBalancer
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: i2scim-mongo-view
  namespace: scim-mongo
roleRef:
  kind: ClusterRole
  apiGroup: rbac.authorization.k8s.io
  name: view
subjects:
  - kind: ServiceAccount
    name: i2scim-mongo
---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  annotations:
    prometheus.io/port: "8080"
    prometheus.io/scheme: http
    prometheus.io/scrape: "true"
    prometheus.io/path: /metrics
  labels:
    app.kubernetes.io/name: i2scim-mongo
    app.kubernetes.io/version: 0.7.0-Alpha
  name: i2scim-mongo
  namespace: scim-mongo
spec:
  serviceName: i2scim-mongo
  replicas: 2
  selector:
    matchLabels:
      app.kubernetes.io/name: i2scim-mongo
      app.kubernetes.io/version: 0.7.0-Alpha
  template:
    metadata:
      annotations:
        prometheus.io/port: "8080"
        prometheus.io/scheme: http
        prometheus.io/scrape: "true"
        prometheus.io/path: /metrics
      labels:
        app.kubernetes.io/name: i2scim-mongo
        app.kubernetes.io/version: 0.7.0-Alpha
      namespace: scim-mongo
    spec:
      containers:
        - env:
            - name: KUBERNETES_NAMESPACE
              valueFrom:
                fieldRef:
                  fieldPath: metadata.namespace
          envFrom:
            - secretRef:
                name: mongo-db-cred
            - configMapRef:
                name: i2scim-mongo-config
            - secretRef:
                name: i2scim-root
          image: independentid/i2scim-mongo:0.7.0-Alpha
          imagePullPolicy: Always
          livenessProbe:
            failureThreshold: 3
            httpGet:
              path: /q/health/live
              port: 8080
              scheme: HTTP
            initialDelaySeconds: 0
            periodSeconds: 30
            successThreshold: 1
            timeoutSeconds: 10
          name: i2scim-mongo
          ports:
            - containerPort: 8080
              name: http
              protocol: TCP
          readinessProbe:
            failureThreshold: 3
            httpGet:
              path: /q/health/ready
              port: 8080
              scheme: HTTP
            initialDelaySeconds: 5
            periodSeconds: 30
            successThreshold: 1
            timeoutSeconds: 10
          volumeMounts:
            - mountPath: /config
              name: configschema
              readOnly: true
              subPath: ""
            - mountPath: /scim
              name: scimroot
              readOnly: false
              subPath: ""
      imagePullSecrets:
        - name: regcred
      serviceAccount: i2scim-mongo
      volumes:
        - configMap:
            defaultMode: 292
            name: i2scim-config-schema
            optional: false
          name: configschema
  volumeClaimTemplates:
    - metadata:
        name: scimroot
      spec:
        storageClassName: i2scimlog
        accessModes:
          - "ReadWriteOnce"
        resources:
          requests:
            storage: 1Gi
