---
apiVersion: v1
kind: ServiceAccount
metadata:
  annotations:
    prometheus.io/port: "8080"
    prometheus.io/scheme: http
    prometheus.io/scrape: "true"
    prometheus.io/path: /metrics
  labels:
    app.kubernetes.io/name: i2scim-mem
    app.kubernetes.io/version: 0.5.0-Alpha
  name: i2scim-mem
  namespace: scim-mem
---
apiVersion: v1
kind: Service
metadata:
  annotations:
    prometheus.io/port: "8080"
    prometheus.io/scheme: http
    prometheus.io/scrape: "true"
    prometheus.io/path: /metrics
  labels:
    app.kubernetes.io/name: i2scim-mem
    app.kubernetes.io/version: 0.5.0-Alpha
  name: i2scim-mem
  namespace: scim-mem
spec:
  ports:
  - name: http
    port: 8080
    targetPort: 8080
  selector:
    app.kubernetes.io/name: i2scim-mem
    app.kubernetes.io/version: 0.5.0-Alpha
  type: LoadBalancer
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: i2scim-mem-view
  namespace: scim-mem
roleRef:
  kind: ClusterRole
  apiGroup: rbac.authorization.k8s.io
  name: view
subjects:
- kind: ServiceAccount
  name: i2scim-mem
---
apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    prometheus.io/port: "8080"
    prometheus.io/scheme: http
    prometheus.io/scrape: "true"
    prometheus.io/path: /metrics
  labels:
    app.kubernetes.io/name: i2scim-mem
    app.kubernetes.io/version: 0.5.0-Alpha
  name: i2scim-mem
  namespace: scim-mem
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: i2scim-mem
      app.kubernetes.io/version: 0.5.0-Alpha
  template:
    metadata:
      annotations:
        prometheus.io/port: "8080"
        prometheus.io/scheme: http
        prometheus.io/scrape: "true"
        prometheus.io/path: /metrics
      labels:
        app.kubernetes.io/name: i2scim-mem
        app.kubernetes.io/version: 0.5.0-Alpha
      namespace: scim-mem
    spec:
      containers:
      - env:
        - name: KUBERNETES_NAMESPACE
          valueFrom:
            fieldRef:
              fieldPath: metadata.namespace
        envFrom:
        - secretRef:
            name: i2scim-root
        - configMapRef:
            name: i2scim-mem-config
        image: independentid/i2scim-mem:0.5.0-Alpha
        imagePullPolicy: Always
        livenessProbe:
          failureThreshold: 3
          httpGet:
            path: /q/health/live
            port: 8080
            scheme: HTTP
          initialDelaySeconds: 0
          periodSeconds: 30
          successThreshold: 1
          timeoutSeconds: 10
        name: i2scim-mem
        ports:
        - containerPort: 8080
          name: http
          protocol: TCP
        readinessProbe:
          failureThreshold: 3
          httpGet:
            path: /q/health/ready
            port: 8080
            scheme: HTTP
          initialDelaySeconds: 5
          periodSeconds: 30
          successThreshold: 1
          timeoutSeconds: 10
        volumeMounts:
        - mountPath: /config
          name: configschema
          readOnly: true
          subPath: ""
        - mountPath: /scim
          name: i2scim-pvc
          readOnly: false
          subPath: ""
      imagePullSecrets:
      - name: regcred
      serviceAccount: i2scim-mem
      volumes:
      - configMap:
          defaultMode: 292
          name: i2scim-config-schema
          optional: false
        name: configschema
      - name: i2scim-pvc
        persistentVolumeClaim:
          claimName: i2scim-pvc
          readOnly: false
