version: '3.8'
volumes:
  prometheus_data: { }
services:
  mongo1:
    container_name: mongo1
    image: mongo:6.0.3
    environment:
      - MONGO_INITDB_ROOT_USERNAME=root
      - MONGO_INITDB_ROOT_PASSWORD=dockTest
      - MONGO_REPLICA_SET_NAME=dbrs
    ports:
      - "30001:30001"
    command: [ "--replSet","dbrs","--keyFile","/data/replica.key","--bind_ip_all","--port","30001" ]
    volumes:
      - ".mongo/replica.key:/data/replica.key"
      - ".mongo/mongo1:/data/db"
  mongo2:
    container_name: mongo2
    image: mongo:6.0.3
    environment:
      - MONGO_INITDB_ROOT_USERNAME=root
      - MONGO_INITDB_ROOT_PASSWORD=dockTest
      - MONGO_REPLICA_SET_NAME=dbrs
    ports:
      - "30002:30002"
    command: [ "--replSet","dbrs","--keyFile","/data/replica.key","--bind_ip_all","--port","30002" ]
    volumes:
      - ".mongo/replica.key:/data/replica.key"
      - ".mongo/mongo2:/data/db"
  mongo3:
    container_name: mongo3
    image: mongo:6.0.3
    environment:
      - MONGO_INITDB_ROOT_USERNAME=root
      - MONGO_INITDB_ROOT_PASSWORD=dockTest
      - MONGO_REPLICA_SET_NAME=dbrs
    ports:
      - "30003:30003"
    command: [ "--replSet","dbrs","--keyFile","/data/replica.key","--bind_ip_all","--port","30003" ]
    volumes:
      - ".mongo/replica.key:/data/replica.key"
      - ".mongo/mongo3:/data/db"
  mongoSetup:
    image: mongo:6.0.3
    depends_on:
      - mongo1
      - mongo2
      - mongo3
    volumes:
      - ".mongo/:/scripts"
    restart: "no"
    entrypoint: [ "bash", "/scripts/mongo_init.sh" ]

  scim_cluster1:
    image: independentid/i2scim-universal:0.7.0-SNAPSHOT
    container_name: scim_cluster1
    ports:
      - "9000:8080"
    depends_on:
      - mongo1
      - mongo2
    volumes:
      - ./config/scim/data1:/scim
    environment:
      - scim.event.enable=false
      - scim.security.enable=true
      - scim.prov.providerClass=com.independentid.scim.backend.mongo.MongoProvider
      - scim.prov.mongo.uri=mongodb://root:dockTest@mongo1:30001,mongo2:30002,mongo3:30003/?retryWrites=true&replicaSet=dbrs&readPreference=primary&serverSelectionTimeoutMS=5000&connectTimeoutMS=10000&authSource=admin&authMechanism=SCRAM-SHA-256
      - scim.signals.enable=false
      - scim.signals.ssf.serverUrl=http://localhost:8888
      - scim.signals.ssf.authorization=<add iat here>
      - scim.signals.pub.iss=cluster.scim.example.com
      - scim.signals.pub.aud=cluster.example.com,monitor.example.com,partner.example.com
      - scim.signals.rcv.iss=cluster.scim.example.com
      - scim.signals.rcv.aud=cluster.example.com
      - scim.signals.rcv.iss.jwksUrl=http://localhost:8888/jwks/cluster.scim.example.com
      - scim.signals.pub.pem.path=/scim/issuer.pem
  scim_cluster2:
    image: independentid/i2scim-universal:0.7.0-SNAPSHOT
    container_name: scim_cluster2
    ports:
      - "9001:8080"
    depends_on:
      - mongo1
      - mongo2
    volumes:
      - ./config/scim/data2:/scim
    environment:
      - scim.event.enable=false
      - scim.security.enable=true
      - scim.prov.providerClass=com.independentid.scim.backend.mongo.MongoProvider
      - scim.prov.mongo.uri=mongodb://root:dockTest@mongo1:30001,mongo2:30002,mongo3:30003/?retryWrites=true&replicaSet=dbrs&readPreference=primary&serverSelectionTimeoutMS=5000&connectTimeoutMS=10000&authSource=admin&authMechanism=SCRAM-SHA-256
      - scim.signals.ssf.serverUrl=http://localhost:8888
      - scim.signals.ssf.authorization=<add iat here>
      - scim.signals.pub.iss=cluster.scim.example.com
      - scim.signals.pub.aud=cluster.example.com,monitor.example.com,partner.example.com
      - scim.signals.rcv.iss=cluster.scim.example.com
      - scim.signals.rcv.aud=cluster.example.com
      - scim.signals.rcv.iss.jwksUrl=http://localhost:8888/jwks/cluster.scim.example.com
      - scim.signals.pub.pem.path=/scim/issuer.pem


