package com.independentid.scim.test;


import static org.assertj.core.api.Assertions.assertThat;
import static org.assertj.core.api.Assertions.fail;

import java.io.IOException;
import java.io.InputStream;
import java.io.StringWriter;
import java.nio.charset.StandardCharsets;
import java.nio.charset.UnsupportedCharsetException;
import java.text.ParseException;
import java.time.Duration;
import java.time.Instant;
import java.util.ArrayList;
import java.util.Iterator;
import java.util.TimeZone;

import javax.annotation.Resource;

import org.apache.http.Header;
import org.apache.http.HttpEntity;
import org.apache.http.HttpHeaders;
import org.apache.http.client.methods.CloseableHttpResponse;
import org.apache.http.client.methods.HttpPost;
import org.apache.http.entity.ContentType;
import org.apache.http.entity.StringEntity;
import org.apache.http.impl.client.CloseableHttpClient;
import org.apache.http.impl.client.HttpClients;
import org.apache.http.util.EntityUtils;
import org.junit.jupiter.api.Assertions;
import org.junit.jupiter.api.MethodOrderer.Alphanumeric;
import org.junit.jupiter.api.Test;
import org.junit.jupiter.api.TestMethodOrder;
import org.junit.jupiter.api.extension.ExtendWith;
import org.junit.runner.RunWith;
import org.slf4j.Logger;
import org.slf4j.LoggerFactory;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.beans.factory.annotation.Value;
import org.springframework.boot.test.context.SpringBootTest;
import org.springframework.boot.test.context.SpringBootTest.WebEnvironment;
import org.springframework.boot.web.server.LocalServerPort;
import org.springframework.core.io.ResourceLoader;
import org.springframework.test.context.ActiveProfiles;
import org.springframework.test.context.ContextConfiguration;
import org.springframework.test.context.TestPropertySource;
import org.springframework.test.context.junit.jupiter.SpringExtension;
import org.springframework.test.context.junit4.SpringRunner;

import com.fasterxml.jackson.core.JsonGenerator;
import com.fasterxml.jackson.databind.JsonNode;
import com.independentid.scim.backend.mongo.MongoProvider;
import com.independentid.scim.protocol.ScimParams;
import com.independentid.scim.protocol.ScimResponse;
import com.independentid.scim.resource.ScimResource;
import com.independentid.scim.schema.SchemaException;
import com.independentid.scim.serializer.JsonUtil;
import com.independentid.scim.server.ConfigMgr;
import com.independentid.scim.server.ScimBootApplication;
import com.independentid.scim.server.ScimException;
import com.mongodb.client.MongoClient;
import com.mongodb.client.MongoClients;
import com.mongodb.client.MongoDatabase;


@ActiveProfiles("testing")
@RunWith(SpringRunner.class)
@ExtendWith(SpringExtension.class)
@SpringBootTest(classes = ScimBootApplication.class, webEnvironment = WebEnvironment.RANDOM_PORT)
@ContextConfiguration(classes = ConfigMgr.class)
@TestMethodOrder(Alphanumeric.class)
@TestPropertySource(properties = {
		"scim.mongodb.test=true",
		"scim.mongodb.dbname=testLoadSCIM",
		"scim.security.enable=false"
})
public class ScimLoadSampleTest {
	
	private static Logger logger = LoggerFactory.getLogger(ScimLoadSampleTest.class);
	
	//private static String userSchemaId = "urn:ietf:params:scim:schemas:core:2.0:User";
	
	@Autowired
	ScimBootApplication app;
	
	@Autowired
	ResourceLoader resourceloader;

	@Resource(name="ConfigMgr")
	private ConfigMgr cmgr ;
	
	@Resource(name="MongoDao")
	public MongoProvider provider;
	
	@Value("${scim.mongodb.uri: mongodb://localhost:27017}")
	private String dbUrl;

	@Value("${scim.mongodb.dbname:SCIMsample}")
	private String scimDbName;
	
	private static MongoClient mclient = null;
	private static MongoDatabase scimDb = null;
	
	@LocalServerPort
	private int port;
	
	//private final static String dataSet = "classpath:/data/user-10pretty.json";
	private final static String dataSet = "classpath:/data/user-5000.json";

	private static ArrayList<ScimResource> data = new ArrayList<ScimResource>();
	private static ArrayList<String> paths = new ArrayList<String>();
	
	private static String readTime = null;
	
	//private static ScimResource user1,user2 = null;
	
	/**
	 * This routine parses JSON data generated by https://randomuser.me
	 * @throws IOException
	 * @throws ScimException 
	 * @throws ParseException 
	 * @throws SchemaException 
	 */
	private void readSampleData() throws IOException, SchemaException, ParseException, ScimException {
		logger.debug("\t\tReading sample data from: "+dataSet);
		Instant start = Instant.now();
		InputStream dataStream = this.resourceloader.getResource(dataSet).getInputStream();
		JsonNode dataNode = JsonUtil.getJsonTree(dataStream);
		
		JsonNode info = dataNode.get("info");
		String seed = info.get("seed").asText();
		String vers = info.get("version").asText();
		logger.debug("\t\tSeed: "+seed+", Vers: "+vers);

		dataNode = dataNode.get("results");
		logger.debug("\t\tJSON Parsed "+dataNode.size()+" records.");
		Iterator<JsonNode> iter = dataNode.elements();
		int cnt=0;
		while (iter.hasNext()) {
			parseUser(iter.next());
			cnt++;
		}
		Instant end = Instant.now();
		Duration dur = Duration.between(start, end);
		readTime = dur.getSeconds()+"."+dur.getNano()+"secs"; 
		logger.info("\t\tMapping complete. "+cnt+" records mapped to SCIM Resource in "+readTime);
	}
	
	private void parseUser(JsonNode mapNode) throws IOException, SchemaException, ParseException, ScimException {
		StringWriter writer = new StringWriter();

		JsonGenerator gen = JsonUtil.getGenerator(writer, true);
		gen.writeStartObject();
		
		gen.writeArrayFieldStart("schemas");
		gen.writeString(ScimParams.SCHEMA_SCHEMA_User);
		gen.writeString(ScimParams.SCHEMA_SCHEMA_Ent_User);
		gen.writeEndArray();
		
		gen.writeObjectFieldStart("meta");
		gen.writeStringField("resourceType", "User");
		gen.writeEndObject();
		
		JsonNode name = mapNode.get("name");
		
		gen.writeFieldName("name");
		gen.writeStartObject();
		
		gen.writeStringField("honorificPrefix", name.get("title").asText());
		gen.writeStringField("familyName", name.get("last").asText());	
		gen.writeStringField("givenName", name.get("first").asText());
		String formatted =  name.get("first").asText() + " " +  name.get("last").asText();
		gen.writeStringField("formatted", formatted);
		gen.writeEndObject();
		
		JsonNode locNode = mapNode.get("location");
		gen.writeFieldName("addresses");
		gen.writeStartArray();
		gen.writeStartObject();
		
		JsonNode snode = locNode.get("street");
		String street = snode.get("number").asText() + " " + snode.get("name").asText();
		gen.writeStringField("streetAddress", street);
		gen.writeStringField("locality", locNode.get("city").asText());
		gen.writeStringField("region", locNode.get("state").asText());
		gen.writeStringField("country", locNode.get("country").asText());
		gen.writeStringField("postalCode", locNode.get("postcode").asText());
		gen.writeStringField("type", "work");
		gen.writeBooleanField("primary", true);
		gen.writeEndObject();		
		gen.writeEndArray();
		
		gen.writeFieldName("emails");
		gen.writeStartArray();
		gen.writeStartObject();
		gen.writeStringField("value", mapNode.get("email").asText());
		gen.writeStringField("type", "work");
		gen.writeEndObject();		
		gen.writeEndArray();
		
		gen.writeStringField("userName", mapNode.path("login").get("username").asText());
		gen.writeStringField("password", mapNode.path("login").get("password").asText());
		gen.writeStringField("externalId", mapNode.path("login").get("uuid").asText());
		
		gen.writeFieldName("phoneNumbers");
		if (mapNode.get("phone") != null) {
		gen.writeStartArray();
		gen.writeStartObject();
		gen.writeStringField("value", mapNode.get("phone").asText());
		gen.writeStringField("type", "work");
		gen.writeEndObject();	
		}
		if (mapNode.get("cell") != null) {
		gen.writeStartObject();
		gen.writeStringField("value", mapNode.get("cell").asText());
		gen.writeStringField("type", "mmobile");
		gen.writeEndObject();		
		}
		gen.writeEndArray();
		
		JsonNode photos = mapNode.get("picture");
		if (photos != null) {
			gen.writeFieldName("photos");
			if (photos.get("large") != null) {
			gen.writeStartArray();
			gen.writeStartObject();
			gen.writeStringField("value", photos.get("large").asText());
			gen.writeStringField("type", "photo");
			gen.writeEndObject();	
			}
			if (photos.get("thumbnail") != null) {
			gen.writeStartObject();
			gen.writeStringField("value", photos.get("thumbnail").asText());
			gen.writeStringField("type", "thumbnail");
			gen.writeEndObject();		
			}
			gen.writeEndArray();
		}
		JsonNode tz = mapNode.path("location").get("timezone");
		String offset = "GMT"+tz.get("offset").asText();
		String[] names = TimeZone.getAvailableIDs(tz.get("offset").asInt());
		logger.debug("Zone names: "+names.toString());
		TimeZone zone = TimeZone.getTimeZone(offset);
		gen.writeStringField("timezone", zone.getID());
	
		gen.close();
		writer.close();
		
		JsonNode scimjnode = JsonUtil.getJsonTree(writer.toString());
		ScimResource user = new ScimResource(cmgr,scimjnode,null,"Users");
		data.add(user);
			
	}

	/**
	 * This test actually resets and re-initializes the SCIM Mongo test database.
	 * @throws IOException 
	 */
	@Test
	public void a_initializeMongo() throws IOException {
	
		logger.info("========== Scim Sample Data ==========");
		logger.info("\tA. Initializing test database: "+scimDbName);
		
		if (mclient == null)
			mclient = MongoClients.create(dbUrl);
		
	
		scimDb = mclient.getDatabase(scimDbName);
		
		scimDb.drop();  // reset the database.
		
		try {
			provider.syncConfig(cmgr.getSchemas(), cmgr.getResourceTypes());
		} catch (IOException e) {
			fail("Failed to initialize test Mongo DB: "+scimDbName);
		}
		try {
			readSampleData();
		} catch (IOException | SchemaException | ParseException | ScimException e) {
			fail("Unable to read in sample data: "+e.getLocalizedMessage(),e);
		}
	}
	/**
	 * This test checks that a JSON user can be parsed into a SCIM Resource
	 */
	@Test
	public void b_ScimAddUserTest() {
		
		logger.info("\tB. Adding Sample Users: Count="+data.size());
		Instant start = Instant.now();

		String req = "http://localhost:"+port+"/Users";

		CloseableHttpClient client = HttpClients.createDefault();

		Iterator<ScimResource> iter = data.iterator();
		
		int i = 0;
		try {
			
			while (iter.hasNext()) {
				i++;
				ScimResource user = iter.next();
				
				StringEntity reqEntity = null;
				String record = null;
				try {
					record = user.toJsonString();
					//logger.debug(record);
					reqEntity = new StringEntity(record,ContentType.create(ScimParams.SCIM_MIME_TYPE,StandardCharsets.UTF_8));
				} catch (UnsupportedCharsetException | ScimException e) {
					fail("Unexpected error serializing sample data: "+e.getLocalizedMessage(),e);
				}
				
				HttpPost post = new HttpPost(req);
				post.setEntity(reqEntity);
				CloseableHttpResponse resp = client.execute(post);
				
				if (resp.getStatusLine().getStatusCode() == ScimResponse.ST_BAD_REQUEST) {
					logger.error("BAD REQUEST for record number: "+i);
					logger.error("Request entity:\n"+record);
					HttpEntity bentity = resp.getEntity();
					String body = EntityUtils.toString(bentity);
					logger.warn("Error received:\n"+body);
					assertThat(body)
					.as("Is a uniqueness error")
					.contains(ScimResponse.ERR_TYPE_UNIQUENESS);
					
					continue;
				} else {
				
					assertThat(resp.getStatusLine().getStatusCode())
					.as("Create user response status of 201")
					.isEqualTo(ScimResponse.ST_CREATED);
				
				}
				
				Header[] hloc = resp.getHeaders(HttpHeaders.LOCATION);
				paths.add(hloc[0].getValue());
				resp.close();
			}
			
			Instant end = Instant.now();
			Duration loadTime = Duration.between(start, end);
			String elapse = loadTime.getSeconds()+"."+loadTime.getNano()+"secs";
			logger.info("----Summary----");
			logger.info("Read time:\t"+readTime);
			logger.info("Create time:\t"+elapse);
			logger.info("Records read: "+data.size()+", created: "+paths.size());
			
			assertThat(paths.size())
				.isEqualTo(data.size());

			
			
		} catch (IOException e) {
			Assertions.fail("Exception occured loading records: "+e.getMessage(),e);
		} finally {
			try {
				client.close();
			} catch (IOException e) {
				// TODO Auto-generated catch block
				e.printStackTrace();
			}
		}				
	}


}
